### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by mrankine** [arp242/git-stats#1]
Nice project!

Sorting columns with numbers doesn't work for me, e.g. `commits` and `avg/day` on the main page, and `commits`, `added` and `removed` on a repo page. Clicking the column header either does nothing or sorts the column incorrectly.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by arp242** [comment]
Thanks; the sort calback returned a bool, which works in Firefox but not Chrome. Pretty confusing.
